# =========================================================
# Application Configuration
# =========================================================

app.url=https://www.saucedemo.com/


# =========================================================
# Browser Configuration
# =========================================================

browser=CHROME
headless=false
execution.mode=local


# =========================================================
# Environment Configuration
# =========================================================

environment=QA


# =========================================================
# Timeout Configuration
# =========================================================

implicit.wait=10
explicit.wait=20
page.load.timeout=30


# =========================================================
# Test Data Configuration
# =========================================================

login.excel.path=src/main/resources/testdata/LoginData.xlsx
login.sheet.name=Login
users.json.path=src/main/resources/testdata/Users.json


# =========================================================
# Reporting Configuration
# =========================================================

screenshot.on.failure=true